import { create } from "zustand";
import { AlphaMatte, MaskStroke } from "../types";
import { applyAllStrokesToMatte, getMaskCoverage } from "../utils/mask.utils";

interface MaskStore {
  mattes: Map<number, AlphaMatte>;
  baseMattes: Map<number, Uint8Array>; // original auto-generated matte without strokes
  strokes: MaskStroke[];
  undoStack: MaskStroke[];
  redoStack: MaskStroke[];
  generatingMask: boolean;

  setMatte: (frameIndex: number, matte: AlphaMatte, isBase?: boolean) => void;
  getMatte: (frameIndex: number) => AlphaMatte | undefined;
  addStroke: (stroke: MaskStroke) => void;
  undo: () => void;
  redo: () => void;
  applyStrokesToMatte: (frameIndex: number) => void;
  clearFrameMask: (frameIndex: number) => void;
  resetFrameToAuto: (frameIndex: number) => void;
  clearAllMasks: () => void;
  setGenerating: (v: boolean) => void;
  hasManualEdits: (frameIndex: number) => boolean;
  getMatteCoverage: (frameIndex: number) => number;
}

export const useMaskStore = create<MaskStore>((set, get) => ({
  mattes: new Map<number, AlphaMatte>(),
  baseMattes: new Map<number, Uint8Array>(),
  strokes: [],
  undoStack: [],
  redoStack: [],
  generatingMask: false,

  setMatte: (frameIndex, matte, isBase = false) => {
    set((state) => {
      const newMattes = new Map(state.mattes);
      const newBaseMattes = new Map(state.baseMattes);
      
      const coverage = getMaskCoverage(matte.data);
      newMattes.set(frameIndex, { ...matte, coverage });

      if (isBase || !newBaseMattes.has(frameIndex)) {
        newBaseMattes.set(frameIndex, new Uint8Array(matte.data));
      }

      return {
        mattes: newMattes,
        baseMattes: newBaseMattes
      };
    });
  },

  getMatte: (frameIndex) => {
    return get().mattes.get(frameIndex);
  },

  addStroke: (stroke) => {
    set((state) => ({
      strokes: [...state.strokes, stroke],
      undoStack: [...state.undoStack, stroke],
      redoStack: [] // clear redo on new action
    }));
    get().applyStrokesToMatte(stroke.frameIndex);
  },

  undo: () => {
    const { undoStack, redoStack, strokes } = get();
    if (undoStack.length === 0) return;

    const lastStroke = undoStack[undoStack.length - 1];
    const newUndoStack = undoStack.slice(0, -1);
    const newRedoStack = [...redoStack, lastStroke];
    const newStrokes = strokes.filter(s => s.id !== lastStroke.id);

    set({
      undoStack: newUndoStack,
      redoStack: newRedoStack,
      strokes: newStrokes
    });

    get().applyStrokesToMatte(lastStroke.frameIndex);
  },

  redo: () => {
    const { redoStack, undoStack, strokes } = get();
    if (redoStack.length === 0) return;

    const strokeToRestore = redoStack[redoStack.length - 1];
    const newRedoStack = redoStack.slice(0, -1);
    const newUndoStack = [...undoStack, strokeToRestore];
    const newStrokes = [...strokes, strokeToRestore];

    set({
      undoStack: newUndoStack,
      redoStack: newRedoStack,
      strokes: newStrokes
    });

    get().applyStrokesToMatte(strokeToRestore.frameIndex);
  },

  applyStrokesToMatte: (frameIndex) => {
    const { mattes, baseMattes, strokes } = get();
    const currentMatte = mattes.get(frameIndex);
    if (!currentMatte) return;

    const baseData = baseMattes.get(frameIndex) || new Uint8Array(currentMatte.width * currentMatte.height);
    const frameStrokes = strokes.filter(s => s.frameIndex === frameIndex);

    const updatedData = applyAllStrokesToMatte(
      baseData,
      frameStrokes,
      currentMatte.width,
      currentMatte.height
    );

    const updatedMatte: AlphaMatte = {
      ...currentMatte,
      data: updatedData,
      hasManualEdits: frameStrokes.length > 0,
      coverage: getMaskCoverage(updatedData),
      lastModified: Date.now()
    };

    set((state) => {
      const newMattes = new Map(state.mattes);
      newMattes.set(frameIndex, updatedMatte);
      return { mattes: newMattes };
    });
  },

  clearFrameMask: (frameIndex) => {
    const { mattes, strokes } = get();
    const currentMatte = mattes.get(frameIndex);
    if (!currentMatte) return;

    const emptyData = new Uint8Array(currentMatte.width * currentMatte.height);
    const clearedMatte: AlphaMatte = {
      ...currentMatte,
      data: emptyData,
      isAutoGenerated: false,
      hasManualEdits: true,
      coverage: 0,
      lastModified: Date.now()
    };

    set((state) => {
      const newMattes = new Map(state.mattes);
      newMattes.set(frameIndex, clearedMatte);
      return {
        mattes: newMattes,
        strokes: strokes.filter(s => s.frameIndex !== frameIndex)
      };
    });
  },

  resetFrameToAuto: (frameIndex) => {
    const { mattes, baseMattes, strokes } = get();
    const currentMatte = mattes.get(frameIndex);
    const baseData = baseMattes.get(frameIndex);
    if (!currentMatte || !baseData) return;

    const restoredMatte: AlphaMatte = {
      ...currentMatte,
      data: new Uint8Array(baseData),
      isAutoGenerated: true,
      hasManualEdits: false,
      coverage: getMaskCoverage(baseData),
      lastModified: Date.now()
    };

    set((state) => {
      const newMattes = new Map(state.mattes);
      newMattes.set(frameIndex, restoredMatte);
      return {
        mattes: newMattes,
        strokes: strokes.filter(s => s.frameIndex !== frameIndex)
      };
    });
  },

  clearAllMasks: () => {
    set({
      mattes: new Map(),
      baseMattes: new Map(),
      strokes: [],
      undoStack: [],
      redoStack: []
    });
  },

  setGenerating: (generatingMask) => set({ generatingMask }),

  hasManualEdits: (frameIndex) => {
    const matte = get().mattes.get(frameIndex);
    return matte ? matte.hasManualEdits : false;
  },

  getMatteCoverage: (frameIndex) => {
    const matte = get().mattes.get(frameIndex);
    return matte?.coverage || 0;
  }
}));
