import { useState, useEffect, useRef, useCallback } from "react";
import { mediapipeService } from "../services/mediapipe.service";
import { useVideoStore } from "../store/videoStore";
import { useMaskStore } from "../store/maskStore";
import { AlphaMatte } from "../types";
import { createOffscreenCanvas } from "../utils/canvas.utils";
import { waitForVideoSeek } from "../utils/video.utils";

export function useMaskingEngine(videoElement: HTMLVideoElement | null) {
  const [isReady, setIsReady] = useState(false);
  const [isFallback, setIsFallback] = useState(false);
  const isCancelledRef = useRef(false);

  const videoSource = useVideoStore((s) => s.videoSource);
  const currentFrameIndex = useVideoStore((s) => s.currentFrameIndex);
  const setProcessingStatus = useVideoStore((s) => s.setProcessingStatus);
  const setMatte = useMaskStore((s) => s.setMatte);
  const setGenerating = useMaskStore((s) => s.setGenerating);

  useEffect(() => {
    let mounted = true;
    mediapipeService.initialize().then(() => {
      if (mounted) {
        setIsReady(true);
        setIsFallback(mediapipeService.isUsingFallback());
      }
    });

    return () => {
      mounted = false;
    };
  }, []);

  const processCurrentFrame = useCallback(async () => {
    if (!videoElement || !videoSource) return;

    try {
      setGenerating(true);
      setProcessingStatus("processing", undefined, `Masking frame ${currentFrameIndex + 1}...`);

      const canvas = createOffscreenCanvas(videoSource.width, videoSource.height);
      const ctx = canvas.getContext("2d", { willReadFrequently: true })!;
      ctx.drawImage(videoElement, 0, 0, videoSource.width, videoSource.height);

      const alphaData = await mediapipeService.segmentFrame(
        canvas,
        currentFrameIndex,
        videoSource.width,
        videoSource.height
      );

      const matte: AlphaMatte = {
        frameIndex: currentFrameIndex,
        width: videoSource.width,
        height: videoSource.height,
        data: alphaData,
        isAutoGenerated: true,
        hasManualEdits: false,
        lastModified: Date.now()
      };

      setMatte(currentFrameIndex, matte, true);
      setProcessingStatus("idle", 100, "Frame mask generated");
    } catch (err: any) {
      setProcessingStatus("error", undefined, err.message || "Segmentation failed");
    } finally {
      setGenerating(false);
    }
  }, [videoElement, videoSource, currentFrameIndex, setGenerating, setProcessingStatus, setMatte]);

  const processAllFrames = useCallback(async () => {
    if (!videoSource) return;

    isCancelledRef.current = false;
    setGenerating(true);
    setProcessingStatus("processing", 0, "Initializing batch segmentation...");

    // Create a dedicated background video element for processing
    const workerVideo = document.createElement("video");
    workerVideo.src = videoSource.url;
    workerVideo.crossOrigin = "anonymous";
    workerVideo.muted = true;
    workerVideo.playsInline = true;

    await new Promise((res) => {
      workerVideo.addEventListener("loadedmetadata", res, { once: true });
    });

    const canvas = createOffscreenCanvas(videoSource.width, videoSource.height);
    const ctx = canvas.getContext("2d", { willReadFrequently: true })!;

    try {
      for (let i = 0; i < videoSource.totalFrames; i++) {
        if (isCancelledRef.current) {
          setProcessingStatus("idle", undefined, "Masking cancelled");
          break;
        }

        workerVideo.currentTime = i / videoSource.fps;
        await waitForVideoSeek(workerVideo);

        ctx.drawImage(workerVideo, 0, 0, videoSource.width, videoSource.height);
        const alphaData = await mediapipeService.segmentFrame(
          canvas,
          i,
          videoSource.width,
          videoSource.height
        );

        const matte: AlphaMatte = {
          frameIndex: i,
          width: videoSource.width,
          height: videoSource.height,
          data: alphaData,
          isAutoGenerated: true,
          hasManualEdits: false,
          lastModified: Date.now()
        };

        setMatte(i, matte, true);

        const progress = Math.round(((i + 1) / videoSource.totalFrames) * 100);
        setProcessingStatus("processing", progress, `Processed frame ${i + 1} of ${videoSource.totalFrames} (${progress}%)`);

        if (i % 3 === 0) {
          await new Promise((r) => setTimeout(r, 0));
        }
      }

      if (!isCancelledRef.current) {
        setProcessingStatus("done", 100, `Completed all ${videoSource.totalFrames} frames`);
      }
    } catch (err: any) {
      setProcessingStatus("error", undefined, err.message || "Batch segmentation error");
    } finally {
      workerVideo.src = "";
      setGenerating(false);
    }
  }, [videoSource, setGenerating, setProcessingStatus, setMatte]);

  const cancelProcessing = useCallback(() => {
    isCancelledRef.current = true;
    setGenerating(false);
    setProcessingStatus("idle", undefined, "Processing stopped");
  }, [setGenerating, setProcessingStatus]);

  return {
    isReady,
    isFallback,
    processCurrentFrame,
    processAllFrames,
    cancelProcessing
  };
}
