// ─── Core Video ────────────────────────────────────────────────────────────────
export interface VideoSource {
  file?: File;
  url: string;           // Object URL or Blob URL
  name: string;
  duration: number;      // seconds
  fps: number;           // frames per second
  width: number;
  height: number;
  totalFrames: number;
}

// ─── Frame ──────────────────────────────────────────────────────────────────────
export interface VideoFrame {
  index: number;         // 0-based frame index
  timestamp: number;     // seconds
  imageData?: ImageData; // Raw pixel data (optional, lazy-loaded)
}

// ─── Alpha Matte ────────────────────────────────────────────────────────────────
export interface AlphaMatte {
  frameIndex: number;
  width: number;
  height: number;
  // Uint8Array of alpha values (0-255), one per pixel, row-major
  // 0 = fully transparent (background), 255 = fully opaque (human)
  data: Uint8Array;
  isAutoGenerated: boolean;   // true = from MediaPipe, false = manual edit
  hasManualEdits: boolean;    // true if user made corrections
  lastModified: number;       // timestamp
  coverage?: number;          // % of pixels covered
}

// ─── Mask Correction Stroke ─────────────────────────────────────────────────────
export interface MaskStrokePoint {
  x: number; // normalized 0-1
  y: number; // normalized 0-1
}

export interface MaskStroke {
  id: string;
  frameIndex: number;
  type: "add" | "erase";    // add = paint human, erase = remove from mask
  brushSize: number;         // pixels
  brushOpacity: number;      // 0.1 - 1.0
  brushFeather: boolean;     // soft edge
  points: MaskStrokePoint[]; // normalized 0-1
}

// ─── Effect Layer ────────────────────────────────────────────────────────────────
export type EffectPresetType = "neon-glow" | "cyber-grid" | "energy-aura" | "speed-lines" | "matrix-rain" | "custom";

export interface EffectFrame {
  frameIndex: number;
  imageData?: ImageData;
  canvas?: HTMLCanvasElement | ImageBitmap;
}

export interface EffectLayer {
  type: "video" | "image-sequence" | "canvas-generated";
  name: string;
  presetType?: EffectPresetType;
  frames?: Map<number, EffectFrame>;
  videoElement?: HTMLVideoElement;
  width: number;
  height: number;
  opacity: number; // 0.0 - 1.0
  blendMode?: GlobalCompositeOperation;
  color?: string;
  speed?: number;
}

// ─── Composite Frame ─────────────────────────────────────────────────────────────
export interface CompositeFrame {
  frameIndex: number;
  // Result = Background + EffectLayer + MaskedHuman
  outputImageData: ImageData;
}

// ─── Editor State ────────────────────────────────────────────────────────────────
export type BrushMode = "add" | "erase";
export type MaskPreviewMode = "overlay" | "cutout" | "composite";
export type ProcessingStatus = "idle" | "loading" | "processing" | "done" | "error";

export interface EditorConfig {
  brushSize: number;          // 5-100px
  brushOpacity: number;       // 0.1 - 1.0
  brushFeather: boolean;      // soft edge vs hard
  brushMode: BrushMode;
  maskPreviewMode: MaskPreviewMode;
  maskOverlayColor: string;   // hex, default "#00FF88"
  maskOverlayOpacity: number; // 0-1
  showOriginalVideo: boolean;
  showEffectLayer: boolean;
  showMask: boolean;
  showBackground: boolean;
  backgroundColor: string;    // hex or "transparent"
  viewMode: "split" | "editor-only" | "composite-only";
}
